# Generated by Django 5.1.6 on 2025-02-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/'),
        ),
    ]
